language: ruby
cache: bundler
before_script: "sh -e /etc/init.d/xvfb start"
script: "bundle exec rake travis"
rvm:
  - 2.1
gemfile:
  - Gemfile
  - gemfiles/rails-3.2.gemfile
  - gemfiles/rails-4.1.gemfile
  - gemfiles/rails-4.2.gemfile
  - gemfiles/rails-master.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/rails-master.gemfile
